### ISSUE TITLE
pynt createstack throwing error

### ISSUE THREAD

**Issue by vikaschouhan** [awslabs/amazon-rekognition-video-analyzer#13]
This is the error I am getting
```
(aws) vi@vi-Vostro-3558:/project/amazon-rekognition-video-analyzer:anaconda2-5.0.1$ pynt createstack
[ build.pyc - Starting task "createstack" ]
Attempting to CREATE 'video-analyzer-stack' stack using CloudFormation.
Waiting until 'video-analyzer-stack' stack status is CREATE_COMPLETE
[ build.pyc - Error in task "createstack" ]
[ build.pyc - Aborting build ]
Traceback (most recent call last):
  File "/pkg/anaconda2-5.0.1/bin/pynt", line 11, in <module>
    sys.exit(main())
  File "/pkg/anaconda2-5.0.1/lib/python2.7/site-packages/pynt/_pynt.py", line 295, in main
    build(sys.argv[1:])
  File "/pkg/anaconda2-5.0.1/lib/python2.7/site-packages/pynt/_pynt.py", line 59, in build
    _run_from_task_names(module,args.tasks)
  File "/pkg/anaconda2-5.0.1/lib/python2.7/site-packages/pynt/_pynt.py", line 109, in _run_from_task_names
    _run(module, logger, task, completed_tasks, True, args, kwargs)
  File "/pkg/anaconda2-5.0.1/lib/python2.7/site-packages/pynt/_pynt.py", line 180, in _run
    task(*(args or []),**(kwargs or {}))
  File "/pkg/anaconda2-5.0.1/lib/python2.7/site-packages/pynt/_pynt.py", line 242, in __call__
    self.func.__call__(*args,**kwargs)
  File "build.py", line 184, in createstack
    cfn_stack_delete_waiter.wait(StackName=stack_name)
  File "/pkg/anaconda2-5.0.1/lib/python2.7/site-packages/botocore/waiter.py", line 53, in wait
    Waiter.wait(self, **kwargs)
  File "/pkg/anaconda2-5.0.1/lib/python2.7/site-packages/botocore/waiter.py", line 323, in wait
    last_response=response,
botocore.exceptions.WaiterError: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state
```
Would appreciate any help on this. Thanks.

**Comment by vikaschouhan** [comment]
Found the problem, that was one or more aws resource permission issue. Looking at the cloudformation console's (https://console.aws.amazon.com/cloudformation/) event logs, I found the root cause.

**Comment by Rajasri21** [comment]
Hi,
Can you tell me which policies you added to resolve the issue. 

Thanks
Rajasri
