### ISSUE TITLE
pynt webui gives error

### ISSUE THREAD

**Issue by rajdarbar** [awslabs/amazon-rekognition-video-analyzer#16]
hello,

when i run **pynt webui** it gives following error 

[ build.pyc - Starting task "webui" ]
Copying Web UI source from 'web-ui/' to build directory.
Retrieving API key from stack 'video-analyzer-stack'.
[ build.pyc - Error in task "webui" ]
[ build.pyc - Aborting build ]
Traceback (most recent call last):
  File "/home/einfochips/kinesisvideo/bin/pynt", line 11, in <module>
    sys.exit(main())
  File "/home/einfochips/kinesisvideo/local/lib/python2.7/site-packages/pynt/_pynt.py", line 295, in main
    build(sys.argv[1:])
  File "/home/einfochips/kinesisvideo/local/lib/python2.7/site-packages/pynt/_pynt.py", line 59, in build
    _run_from_task_names(module,args.tasks)
  File "/home/einfochips/kinesisvideo/local/lib/python2.7/site-packages/pynt/_pynt.py", line 109, in _run_from_task_names
    _run(module, logger, task, completed_tasks, True, args, kwargs)
  File "/home/einfochips/kinesisvideo/local/lib/python2.7/site-packages/pynt/_pynt.py", line 180, in _run
    task(*(args or []),**(kwargs or {}))
  File "/home/einfochips/kinesisvideo/local/lib/python2.7/site-packages/pynt/_pynt.py", line 242, in __call__
    self.func.__call__(*args,**kwargs)
  File "build.py", line 326, in webui
    LogicalResourceId=cfn_params_dict["ApiGatewayRestApiNameParameter"]
  File "/home/einfochips/kinesisvideo/local/lib/python2.7/site-packages/botocore/client.py", line 317, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/einfochips/kinesisvideo/local/lib/python2.7/site-packages/botocore/client.py", line 615, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the DescribeStackResource operation: Resource VidAnalyzerRestApi does not exist for stack video-analyzer-stack

**Comment by RATHINAMOORTHY** [comment]
Hi I am getting the same error..any solution?
