### ISSUE TITLE
createstack error

### ISSUE THREAD

**Issue by maneeshsri** [awslabs/amazon-rekognition-video-analyzer#20]
Getting stack ROLLBACK_COMPLETE status.

[ build.pyc - Error in task "createstack" ]
[ build.pyc - Aborting build ]
Traceback (most recent call last):
  File "/usr/local/bin/pynt", line 9, in <module>
    load_entry_point('pynt==0.8.1', 'console_scripts', 'pynt')()
  File "/usr/local/lib/python2.7/dist-packages/pynt/_pynt.py", line 295, in main
    build(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/pynt/_pynt.py", line 59, in build
    _run_from_task_names(module,args.tasks)
  File "/usr/local/lib/python2.7/dist-packages/pynt/_pynt.py", line 109, in _run_from_task_names
    _run(module, logger, task, completed_tasks, True, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pynt/_pynt.py", line 180, in _run
    task(*(args or []),**(kwargs or {}))
  File "/usr/local/lib/python2.7/dist-packages/pynt/_pynt.py", line 242, in __call__
    self.func.__call__(*args,**kwargs)
  File "build.py", line 184, in createstack
    cfn_stack_delete_waiter.wait(StackName=stack_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/waiter.py", line 53, in wait
    Waiter.wait(self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/waiter.py", line 323, in wait
    last_response=response,
botocore.exceptions.WaiterError: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state

**Comment by RooCoder** [comment]
Duplicate. Please check the other issue comments. Even I am stuck though
